### ISSUE TITLE
Interview request

### ISSUE THREAD

**Issue by brucou** [brahmosjs/brahmos#92]
Hi @s-yadav 

would you be interested in an interview on Brahmos? I would like to write a Q&A article for [infoq](infoq.com) if you would find the time. Let me know what you think. If that works for you I will leave you my email here so we can continue the conversation there.

Congratulations for the work done so far!

**Comment by s-yadav** [comment]
Thanks @brucou
And sure, I would love to do that.

**Comment by brucou** [comment]
@s-yadav great! please write me here bcouriol@sparks.network so I have your email, and please delete this message so I don't get spammed to death :-)
