### ISSUE TITLE
Why both webpack and rollup being used? 

### ISSUE THREAD

**Issue by kanishk30** [brahmosjs/brahmos#96]
Hi. It is more of a question than an issue. 
I was going through package.json. I found that both rollup and webpack are been imported as module bundler. 
I read https://link.medium.com/cZyEq3RaK9 on how two can co-exist. 
Is Brahmos usecase the same?

**Comment by s-yadav** [comment]
Rollup does not add up any runtime. So it's great for bundling library for a smaller footprint. But webpack shines in its dev server. 
So using rollup to create bundles, and webpack to run dev server for running examples in local development.

Mixing tooling is fine unless they are adding up the complexity and solving the right problem.
